"""Registration of a freshly predicted model in the performance configurations.

Instead of editing the configurations that are tracked in git, a small module
is generated per model.  It imports the base configuration (so all the models
that are active there are still drawn) and adds the entries of the new model.
The tracked configuration can additionally be updated in place with
``--update-base-config``.
"""

import importlib.util
import os
import pprint
import re
import sys

from law_tasks import naming
from law_tasks.config import settings

GENERATED_HEADER = '''"""Generated by the law task hh4b.RegisterModel -- do not edit by hand.

Model: {key}
Base configuration: {base}
"""

import importlib.util as _importlib_util
import os as _os

_BASE_CONFIG = "{base}"


def _load_base(path):
    spec = _importlib_util.spec_from_file_location(
        "law_base_" + _os.path.splitext(_os.path.basename(path))[0], path
    )
    module = _importlib_util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_base = _load_base(_BASE_CONFIG)

run2_dataset_MC = getattr(_base, "run2_dataset_MC", "")
run2_dataset_DATA = getattr(_base, "run2_dataset_DATA", "")
roc_dict = dict(getattr(_base, "roc_dict", {{}}))

spanet_dict = {baseline}
true_dict = dict(_base.true_dict)

spanet_dict[{key!r}] = {spanet_entry}

true_dict[{true_key!r}] = {true_entry}
'''


def load_config_module(path):
    """Import a performance configuration module from its file path."""
    path = os.path.abspath(path)
    name = "law_cfg_" + os.path.splitext(os.path.basename(path))[0]
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def used_colors(modules):
    """Colors already taken by an active entry of any of ``modules``."""
    colors = []
    for module in modules:
        for entry in getattr(module, "spanet_dict", {}).values():
            color = entry.get("color")
            if color:
                colors.append(color)
    return colors


def resolve_true_key(modules, test_file, fallback):
    """Return the ``true_dict`` key to use for ``test_file``.

    Models that only differ by a training setting share their truth file; by
    matching on the resolved path the pipeline reuses the key that is already
    there instead of adding a duplicate.  When the derived key is taken by a
    *different* file, a numbered suffix is appended so nothing is overwritten.
    """
    target = os.path.realpath(os.path.expandvars(test_file))

    known = {}
    for module in modules:
        for key, entry in getattr(module, "true_dict", {}).items():
            name = entry.get("name")
            if not name:
                continue
            path = os.path.realpath(os.path.expandvars(name))
            if path == target:
                return key, True
            known.setdefault(key, path)

    key, index = fallback, 1
    while key in known:
        index += 1
        key = "{}_v{}".format(fallback, index)
    return key, False


def build_entries(
    key,
    prediction_file,
    test_file,
    color,
    label=None,
    true_key=None,
    vbf=True,
    klambda=None,
    extra_spanet=None,
    extra_true=None,
):
    """Build the ``spanet_dict`` and ``true_dict`` entries of one model."""
    token_spanet, token_true = naming.extra_entries(key)

    spanet_entry = {
        "file": prediction_file,
        "true": true_key or naming.derive_true_key(key),
        "label": label or naming.derive_label(key),
        "color": color,
    }
    if vbf:
        spanet_entry["vbf"] = True
    spanet_entry.update(token_spanet)
    spanet_entry.update(extra_spanet or {})

    true_entry = {"name": test_file, "klambda": klambda or settings().klambda}
    true_entry.update(token_true)
    true_entry.update(extra_true or {})

    return spanet_entry, true_entry


def _format(dictionary, indent=0):
    text = pprint.pformat(dictionary, indent=4, width=100, sort_dicts=False)
    if indent:
        pad = " " * indent
        text = ("\n" + pad).join(text.splitlines())
    return text


def render_module(key, base_config, spanet_entry, true_key, true_entry, baseline_models="all"):
    """Return the source code of the generated configuration module."""
    if baseline_models == "all":
        baseline = "dict(_base.spanet_dict)"
    elif baseline_models in ("none", ""):
        baseline = "{}"
    else:
        keep = [m.strip() for m in baseline_models.split(",") if m.strip()]
        baseline = (
            "{{k: v for k, v in _base.spanet_dict.items() if k in {!r}}}".format(keep)
        )

    return GENERATED_HEADER.format(
        key=key,
        base=os.path.abspath(base_config),
        baseline=baseline,
        spanet_entry=_format(spanet_entry),
        true_key=true_key,
        true_entry=_format(true_entry),
    )


def write_module(path, source):
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, "w") as fobj:
        fobj.write(source)
    return path


# ---------------------------------------------------------------------------
# optional in place update of the tracked configurations
# ---------------------------------------------------------------------------


def _entry_source(key, entry, indent=4):
    pad = " " * indent
    lines = ["{}{!r}: {{".format(pad, key)]
    for name, value in entry.items():
        lines.append("{}{!r}: {!r},".format(pad * 2, name, value))
    lines.append("{}}},".format(pad))
    return "\n".join(lines) + "\n"


def _dict_end(text, dict_name):
    """Line index of the closing brace of a top level ``<dict_name> = {`` block."""
    match = re.search(r"^{}\s*=\s*\{{".format(re.escape(dict_name)), text, re.M)
    if not match:
        raise ValueError("no top level '{}' found".format(dict_name))

    lines = text[: match.start()].count("\n")
    all_lines = text.splitlines(keepends=True)
    for index in range(lines + 1, len(all_lines)):
        if all_lines[index].startswith("}"):
            return all_lines, index
    raise ValueError("no closing brace found for '{}'".format(dict_name))


def _has_active_key(text, dict_name, key):
    all_lines, end = _dict_end(text, dict_name)
    start = next(
        i for i, line in enumerate(all_lines) if re.match(r"^{}\s*=\s*\{{".format(re.escape(dict_name)), line)
    )
    pattern = re.compile(r"^\s*['\"]{}['\"]\s*:".format(re.escape(key)))
    return any(pattern.match(line) for line in all_lines[start:end])


def update_base_config(path, key, spanet_entry, true_key, true_entry):
    """Append the entries to a tracked configuration file, if not present yet.

    Returns the list of dictionaries that were actually modified.
    """
    with open(path) as fobj:
        text = fobj.read()

    modified = []

    if not _has_active_key(text, "spanet_dict", key):
        all_lines, end = _dict_end(text, "spanet_dict")
        all_lines.insert(end, _entry_source(key, spanet_entry))
        text = "".join(all_lines)
        modified.append("spanet_dict")

    if not _has_active_key(text, "true_dict", true_key):
        all_lines, end = _dict_end(text, "true_dict")
        all_lines.insert(end, _entry_source(true_key, true_entry))
        text = "".join(all_lines)
        modified.append("true_dict")

    if modified:
        with open(path, "w") as fobj:
            fobj.write(text)

    return modified
